apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rayservice-sample
spec:
  serveConfigV2: |
    applications:
    - name: translator
      route_prefix: /translator
      import_path: main:translator_app
      runtime_env: {}
      deployments:
      - name: translator
        max_ongoing_requests: 5
        autoscaling_config:
          min_replicas: 1
          initial_replicas: null
          max_replicas: 1
          target_ongoing_requests: 2.0
          metrics_interval_s: 10.0
          look_back_period_s: 30.0
          smoothing_factor: 1.0
          upscale_smoothing_factor: null
          downscale_smoothing_factor: null
          upscaling_factor: null
          downscaling_factor: null
          downscale_delay_s: 600.0
          downscale_to_zero_delay_s: null
          upscale_delay_s: 30.0
          aggregation_function: mean
          policy:
            policy_function: ray.serve.autoscaling_policy:default_autoscaling_policy
        ray_actor_options:
          num_cpus: 0.2
          num_gpus: 0.0
    - name: chain
      route_prefix: /chain
      import_path: main:chain_app
      runtime_env: {}
      deployments:
      - name: Adder
      - name: Multiplier
      - name: Chain
    - name: stream
      route_prefix: /stream
      import_path: main:stream_app
      runtime_env: {}
      deployments:
      - name: Streamer
      - name: Stream
  rayClusterConfig:
    rayVersion: 2.46.0
    headGroupSpec:
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray:2.46.0
            resources:
              limits:
                cpu: 2
                memory: 5Gi
              requests:
                cpu: 2
                memory: 2Gi
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 5
      groupName: small-group
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray:2.46.0
            resources:
              limits:
                cpu: '1'
                memory: 2Gi
              requests:
                cpu: 500m
                memory: 2Gi
